all: hello1 hello2 hello3

hello1: hello_world_1.c
	zcc +zx -vn -lndos -create-app -o hello_1_out hello_world_1.c

hello2: hello_world_2.c
	zcc +zx -vn -lndos -create-app -o hello_2_out hello_world_2.c

hello3: hello_world_3.c
	zcc +zx -vn -lndos -create-app -o hello_3_out hello_world_3.c
